port: 7891
socks-port: 7892
redir-port: 7893
mixed-port: 7890
tproxy-port: 7894
allow-lan: true
bind-address: "*"
lan-allowed-ips:
  - 127.0.0.1/32
  - 192.168.31.0/24
mode: rule
ipv6: false
keep-alive-interval: 15
keep-alive-idle: 15
disable-keep-alive: false
find-process-mode: strict
unified-delay: true
tcp-concurrent: true
profile:
  store-selected: true
  store-fake-ip: true
external-controller: 0.0.0.0:9090
secret: "wen624978"
external-ui: ui
external-ui-url: "https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip" 
global-client-fingerprint: chrome
geodata-mode: false
geodata-loader: memconservative
geo-auto-update: true
geo-update-interval: 24
geox-url:
  geoip: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat"
  geosite: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country.mmdb"
  asn: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb"
log-level: warning
interface-name: ""





sniffer:
  enable: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-dns-mapping: true
  parse-pure-ip: true
  force-domain:
    - "+.v2ex.com"
  skip-domain:
    - '*.alipay.com'
    - '*.tenpay.com'
    - '*.paypal.com'
    - '*.unionpay.com'
    - '*.unionpayintl.com'
    - '*.icbc.com.cn'
    - '*.ccb.com'
    - '*.abchina.com'
    - '*.boc.cn'
    - '*.psbc.com'
    - '*.bankcomm.com'
    - '*.cmbchina.com'
    - '*.spdb.com.cn'
    - '*.citicbank.com'
    - '*.cebbank.com'
    - '*.cib.com.cn'
    - '*.pingan.com'
    - '*.windows.com'
    - '*.live.com'
    - '*.qq.com'
    - '*.tencent.com'
    - '*.wechat.com'
    - 'xmpush.xiaomi.com'
    - 'Mijia Cloud'
    - '*.miwifi.com'
    - '*.tplinkcloud.com'
    - '*.tplinkra.com'
    - '*.oray.com'
    - '*.oray.net'
    - 'localhost'
    - '*.local'
    - '*.lan'
    - '*.corp'
    - '*.internal'
    - '*.test'
  skip-dst-address:
    - '127.0.0.0/8'
    - '10.0.0.0/8'
    - '172.16.0.0/12'
    - '192.168.0.0/16'
    - '100.64.0.0/10'
    - '169.254.0.0/16'
    - '224.0.0.0/4'
    - '::1/128'
    - 'fc00::/7'
    - 'fe80::/10'

# 入站  
tun:
  enable: true
  stack: mixed
  device: Meta
  auto-route: true
  auto-detect-interface: true
  strict-route: true
  dns-hijack:
    - any:53
    - tcp://any:53
  route-exclude-address:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
    - 224.0.0.0/4
    - 127.0.0.1/32
    - fc00::/7
    - fe80::/10
  udp-timeout: 300

# DNS模块
dns:
  enable: true
  cache-algorithm: arc
  prefer-h3: false
  use-hosts: false
  use-system-hosts: true
  respect-rules: false
  listen: 0.0.0.0:1053
  ipv6: false
  default-nameserver:
    - 111.11.1.1
    - 223.5.5.5
    - 119.29.29.29
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - '*.lan'
    - '*.local'
    - '+.msftconnecttest.com'
    - '+.msftncsi.com'
    - 'captive.apple.com'
    - 'connectivitycheck.gstatic.com'
    - 'time.*.com'  
    - 'ntp.aliyun.com'
    - 'ntp.tencent.com'
    - 'speed.cloudflare.com'
    - '+.speedtest.net'
    - '+.microsoft.com'
    - '+.live.com'
    - '+.market.xiaomi.com'
  nameserver-policy:
    '+.local': 'system'
    'rule-set:cn_domain,microsoft_domain,apple_domain':
      - https://dns.alidns.com/dns-query#DIRECT
      - https://doh.pub/dns-query#DIRECT
    'rule-set:geolocation-!cn_domain':
      - https://dns.google/dns-query#Google&h3=true
      - https://cloudflare-dns.com/dns-query#节点选择&h3=true
    "+.ligon.top":
      - 8.8.8.8
  nameserver:
    - https://dns.google/dns-query#Google&h3=true
    - https://cloudflare-dns.com/dns-query#节点选择&h3=true
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query#国内平台
    - https://doh.pub/dns-query#国内平台

proxy-providers:
  自建:
    type: http
   
    interval: 86400
    override:
      additional-prefix: "自建:"
    health-check:
      enable: true
      url: "http://www.apple.com/library/test/success.html"
      interval: 600




ping: &ping
    type: select
    proxies:
      - 节点选择
      - DIRECT
      - 机场 
    use:
      - 自建
    url: "http://www.apple.com/library/test/success.html"
    interval: 300
    lazy: true
    timeout: 5000
    max-failed-times: 5


proxy-groups:


  - name: 节点选择
    type: select
    proxies:
      - DIRECT
      - 机场 
    use:
      - 自建
    url: "http://www.apple.com/library/test/success.html"
    interval: 300
    lazy: true
    timeout: 5000
    max-failed-times: 5
    icon: https://github.com/ligonfei/Ligonfei/raw/refs/heads/main/%E8%8A%82%E7%82%B9%E9%80%89%E6%8B%A9.svg


  - name: 机场
    type: select
    use:
      - 机场
    icon: https://github.com/ligonfei/Ligonfei/blob/main/Airport.png?raw=true


  - name: 游戏平台
    <<: *ping
    icon: https://github.com/ligonfei/Ligonfei/blob/main/Game.png?raw=true


  - name: YouTube
    <<: *ping
    icon: https://github.com/ligonfei/Ligonfei/blob/main/YouTube.png?raw=true


  - name: Spotify
    <<: *ping 
    icon: https://github.com/ligonfei/Ligonfei/blob/main/Spotify.png?raw=true


  - name: 推特
    <<: *ping 
    icon: https://github.com/ligonfei/Ligonfei/blob/main/Twitter.png?raw=true


  - name: Facebook
    <<: *ping
    icon: https://github.com/ligonfei/Ligonfei/blob/main/Facebook.png?raw=true


  - name: Google
    <<: *ping
    icon: https://github.com/ligonfei/Ligonfei/blob/main/google.png?raw=true


  - name: AI
    <<: *ping
    icon: https://github.com/ligonfei/Ligonfei/raw/refs/heads/main/chatgpt.svg


  - name: GitHub
    <<: *ping
    icon: https://github.com/ligonfei/Ligonfei/blob/main/GitHub.png?raw=true


  - name: Bing
    <<: *ping
    icon: https://github.com/ligonfei/Ligonfei/raw/refs/heads/main/bing.svg


  - name: Microsoft
    <<: *ping
    icon: https://github.com/ligonfei/Ligonfei/raw/refs/heads/main/microsoft.svg


  - name: 交易所
    <<: *ping
    icon: https://github.com/ligonfei/Ligonfei/raw/refs/heads/main/%E4%BA%A4%E6%98%93%E6%89%80.svg


  - name: TikTok
    <<: *ping
    icon: https://github.com/ligonfei/Ligonfei/blob/main/tiktok.png?raw=true


  - name: Telegram
    <<: *ping
    icon: https://github.com/ligonfei/Ligonfei/blob/main/Telegram.png?raw=true


  - name: NETFLIX
    <<: *ping
    icon: https://github.com/ligonfei/Ligonfei/blob/main/netflix.png?raw=true


  - name: Disney+
    <<: *ping
    icon: https://github.com/ligonfei/Ligonfei/blob/main/Disney.png?raw=true


  - name: Speedtest
    <<: *ping
    icon: https://github.com/ligonfei/Ligonfei/blob/main/Speedtest.png?raw=true


  - name: Apple
    <<: *ping
    icon: https://github.com/ligonfei/Ligonfei/blob/main/appleclassic.png?raw=true


  - name: 国内平台
    type: select
    proxies:
      - DIRECT
      - 节点选择
      - 机场
    icon: https://github.com/ligonfei/Ligonfei/blob/main/China.png?raw=true
    url: "http://www.apple.com/library/test/success.html"
    interval: 300
    lazy: true
    timeout: 5000
    max-failed-times: 5


  - name: 广告拦截
    type: select
    proxies:
      - DIRECT
      - REJECT
    icon: https://github.com/ligonfei/Ligonfei/blob/main/adguard.png?raw=true
    url: "http://www.apple.com/library/test/success.html"
    interval: 300
    lazy: true
    timeout: 5000
    max-failed-times: 5


  - name: 漏网之鱼
    <<: *ping
    icon: https://github.com/ligonfei/Ligonfei/raw/refs/heads/main/fish.svg


rules:
  - RULE-SET,ads1_domain,广告拦截 
  - RULE-SET,ads2_domain,广告拦截 
  - RULE-SET,ads3_domain,广告拦截

  - RULE-SET,private_domain,国内平台 
  - RULE-SET,private_ip,国内平台

  - RULE-SET,steam_domain,游戏平台
  - RULE-SET,xbox_domain,游戏平台
  - RULE-SET,rockstar_domain,游戏平台
  - RULE-SET,ubisoft_domain,游戏平台
  - RULE-SET,epic_domain,游戏平台
  - RULE-SET,ea_domain,游戏平台
  - RULE-SET,gog_domain,游戏平台

  - RULE-SET,binance_domain,交易所
  - RULE-SET,OKX_domain,交易所

  - RULE-SET,youtube_domain,YouTube

  - RULE-SET,spotify_domain,Spotify

  - RULE-SET,x_domain,推特
  - RULE-SET,twitter_domain,推特
  - RULE-SET,twitter_ip,推特

  - RULE-SET,facebook_domain,Facebook
  - RULE-SET,facebook_ip,Facebook

  - RULE-SET,telegram_domain,Telegram
  - RULE-SET,telegram_ip,Telegram

  - RULE-SET,ai_domain,AI
  - RULE-SET,ai_ip,AI

  - RULE-SET,speedtest_domain,Speedtest

  - RULE-SET,tiktok_domain,TikTok

  - RULE-SET,disney_domain,Disney+

  - RULE-SET,netflix_domain,NETFLIX
  - RULE-SET,netflix_ip,NETFLIX

  - RULE-SET,apple_domain,Apple

  - RULE-SET,github_domain,GitHub

  - RULE-SET,bing_domain,Bing

  - RULE-SET,microsoft_domain,Microsoft

  - RULE-SET,google_domain,Google
  - RULE-SET,google_ip,Google

  - RULE-SET,gfw_domain, 节点选择

  - RULE-SET,cn_domain,国内平台
  - RULE-SET,cn_ip,国内平台

  - MATCH,漏网之鱼

rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}  
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}

rule-providers: 
  rockstar_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/rockstar.mrs"}
  xbox_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/xbox.mrs"}
  ubisoft_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/ubisoft.mrs"}
  ea_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/ea.mrs"}
  epic_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/epicgames.mrs"}
  steam_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/steam.mrs"}
  gog_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/gog.mrs"}
  private_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/private.mrs"}
  ai_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-ai-!cn.mrs"}
  youtube_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/youtube.mrs"}
  x_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/x.mrs"}
  twitter_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/twitter.mrs"}
  facebook_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/facebook.mrs"}
  google_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/google.mrs"}
  github_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/github.mrs"}
  telegram_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/telegram.mrs"}
  netflix_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/netflix.mrs"}
  disney_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/disney.mrs"}
  bing_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/bing.mrs"}
  microsoft_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/microsoft.mrs"}
  spotify_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/spotify.mrs"}
  binance_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/binance.mrs"}
  OKX_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/okx.mrs"}
  apple_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/apple.mrs"}
  speedtest_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-speedtest.mrs"}
  tiktok_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/tiktok.mrs"}
  gfw_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/gfw.mrs"}
  geolocation-cn_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/geolocation-cn.mrs"}
  geolocation-!cn_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/geolocation-!cn.mrs"}
  cn_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/cn.mrs"}
  ads1_domain: { <<: *domain, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-ads-all.mrs"}
  ads2_domain: { <<: *domain, url: "https://raw.githubusercontent.com/privacy-protection-tools/anti-ad.github.io/master/docs/mihomo.mrs"}
  ads3_domain: { <<: *domain, url: "https://raw.githubusercontent.com/Cats-Team/AdRules/main/adrules-mihomo.mrs"}
  private_ip: { <<: *ip, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/private.mrs"}
  cn_ip: { <<: *ip, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/cn.mrs"}
  ai_ip: { <<: *ip, url:  "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/ai.mrs"}
  google_ip: { <<: *ip, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/google.mrs"}
  twitter_ip: { <<: *ip, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/twitter.mrs"}
  telegram_ip: { <<: *ip, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/telegram.mrs"}
  netflix_ip: { <<: *ip, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/netflix.mrs"}
  facebook_ip: { <<: *ip, url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/facebook.mrs"}

