# 基本配置
mixed-port: 7890
redir-port: 9797
tproxy-port: 9898
socks-port: 7891
ipv6: true
mode: Rule
allow-lan: true
unified-delay: true
tcp-concurrent: true
log-level: warning
bind-address: "*"
find-process-mode: strict
external-controller: 0.0.0.0:9090
external-ui: "zash"
external-ui-url: "https://github.com/Zephyruso/zashboard/releases/latest/download/dist.zip"
secret: ""

# 局域网免密
skip-auth-prefixes:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
  - 127.0.0.1/8
  - 100.64.0.0/10

# 节点记忆
profile:
  store-selected: true
  store-fake-ip: true

# 时间校准
ntp:
  enable: true
  write-to-system: true
  server: ntp.ntsc.ac.cn
  port: 123
  interval: 60

# hosts模块
hosts:
  mtalk.google.com: 142.250.107.188
  alt1-mtalk.google.com: 74.125.200.188
  alt2-mtalk.google.com: 192.178.220.188
  alt3-mtalk.google.com: 74.125.131.188
  alt4-mtalk.google.com: 209.85.144.188
  alt5-mtalk.google.com: 74.125.126.188
  alt6-mtalk.google.com: 142.250.115.188
  alt7-mtalk.google.com: 192.178.131.188
  alt8-mtalk.google.com: 172.253.132.188

# 嗅探模块
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 5228, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - "+.v2ex.com"
  skip-domain:
    - "Mijia Cloud"
    - "+.push.apple.com"
  skip-dst-address:
    - 91.105.192.0/23
    - 91.108.4.0/22
    - 91.108.8.0/21
    - 91.108.16.0/21
    - 91.108.56.0/22
    - 95.161.64.0/20
    - 149.154.160.0/20
    - 185.76.151.0/24
    - 2001:67c:4e8::/48
    - 2001:b28:f23c::/47
    - 2001:b28:f23f::/48
    - 2a0a:f280:203::/48

# 网卡模块
tun:
  exclude-uid: []
  include-uid: []
  enable: true
  device: Meta
  stack: gvisor
  dns-hijack:
    - any:53
    - tcp://any:53
  udp-timeout: 300
  auto-route: true
  strict-route: false
  auto-redirect: false
  auto-detect-interface: true
  endpoint-independent-nat: true
  route-exclude-address:
    - 10.0.0.0/8
    - 127.0.0.0/8
    - 169.254.0.0/16
    - 172.16.0.0/12
    - 192.168.0.0/16
    - 224.0.0.0/4

# DNS模块
dns:
  enable: true
  use-hosts: true
  ipv6: false
  cache-algorithm: arc
  prefer-h3: false
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-range6: fdfe:dcba:9876::1/64
  fake-ip-filter-mode: rule
  fake-ip-filter:
    - DOMAIN-SUFFIX,googleapis.cn,fake-ip
    - DOMAIN-SUFFIX,rom.miui.com,real-ip
    - DOMAIN-SUFFIX,miui.com,real-ip
    - RULE-SET,cn_domain,real-ip
    - RULE-SET,private_domain,real-ip
    - RULE-SET,Fake-IP-Filter,real-ip
    - DOMAIN-KEYWORD,mtalk.google,real-ip
  respect-rules: true
  default-nameserver:
    - 223.5.5.5
    - 1.12.12.12
  direct-nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  nameserver-policy:
    "RULE-SET:cn_domain":
      - https://dns.alidns.com/dns-query
      - https://doh.pub/dns-query
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query

# 锚点定义
_anchors:
  provider_base: &p
    type: http
    interval: 7200
    health-check:
      enable: true
      url: "https://www.gstatic.com/generate_204"
      interval: 600

  test_config: &test_config
    url: "https://www.gstatic.com/generate_204"
    interval: 600
    lazy: false
    timeout: 5000

  all_providers: &all_providers
    - 自建
    - 雪山
    - 西部数据
    - 山海
    - Kitty

  url_test_base: &url_test_base
    type: url-test
    <<: *test_config
    hidden: true

  airport_group: &airport_group
    <<: *url_test_base

  country_nodes: &country_nodes
    <<: *url_test_base
    use: *all_providers
    tolerance: 50

  platform_group: &platform_group
    type: select
    proxies:
      - DIRECT
      - 节点选择
      - 自动选择
      - 自建
      - 雪山
      - 西部数据
      - 山海
      - Kitty
      - 香港节点
      - 台湾节点
      - 美国节点
      - 日本节点
      - 韩国节点
      - 新加坡节点
    interval: 60
    lazy: false
    timeout: 5000

  rule_domain_base: &domain
    type: http
    interval: 86400
    behavior: domain
    format: mrs
  
  rule_ip_base: &ip
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs

# 订阅地址
proxy-providers:
  自建:


# 代理策略组配置 (使用2.yaml的策略组)
proxy-groups:
  - name: 节点选择
    type: select
    proxies:
      - DIRECT
      - 自建
      - 雪山
      - 西部数据
      - 山海
      - Kitty
    <<: *test_config
    icon: "https://raw.githubusercontent.com/ligonfei/Ligonfei/main/nodeselection.png"

  - name: 自动选择
    type: url-test
    use: *all_providers
    <<: *test_config
    icon: "https://raw.githubusercontent.com/ligonfei/Ligonfei/main/autoselection.png"

  - name: 自建
    <<: *airport_group
    use: [自建]
    icon: "https://raw.githubusercontent.com/ligonfei/Ligonfei/main/TestFlight.png"

  - name: 雪山
    <<: *airport_group
    use: [雪山]
    icon: "https://raw.githubusercontent.com/ligonfei/Ligonfei/main/xueshan.png"

  - name: 西部数据
    <<: *airport_group
    use: [西部数据]
    icon: "https://raw.githubusercontent.com/ligonfei/Ligonfei/main/WestData.png"

  - name: 山海
    <<: *airport_group
    use: [山海]
    icon: "https://shanhai.one/images/logo.png?raw=true"

  - name: Kitty
    <<: *airport_group
    use: [Kitty]
    icon: "https://github.com/ligonfei/Ligonfei/blob/main/kitty.jpg?raw=true"

  - name: 密码管理器
    <<: *platform_group
    icon: "https://raw.githubusercontent.com/ligonfei/Ligonfei/main/1password.png"

  - name: 交易所
    <<: *platform_group
    icon: "https://raw.githubusercontent.com/ligonfei/Ligonfei/main/BTC.png"

  - name: AI
    <<: *platform_group
    icon: "https://raw.githubusercontent.com/ligonfei/Ligonfei/main/chatgpt.png"

  - name: Speedtest
    <<: *platform_group
    icon: "https://raw.githubusercontent.com/ligonfei/Ligonfei/main/Speedtest.png"

  - name: Telegram
    <<: *platform_group
    icon: "https://raw.githubusercontent.com/ligonfei/Ligonfei/main/Telegram.png"

  - name: 推特
    <<: *platform_group
    icon: "https://raw.githubusercontent.com/ligonfei/Ligonfei/main/Twitter.png"

  - name: YouTube
    <<: *platform_group
    icon: "https://raw.githubusercontent.com/ligonfei/Ligonfei/main/YouTube.png"

  - name: Disney+
    <<: *platform_group
    icon: "https://raw.githubusercontent.com/ligonfei/Ligonfei/main/Disney.png"

  - name: NETFLIX
    <<: *platform_group
    icon: "https://raw.githubusercontent.com/ligonfei/Ligonfei/main/netflix.png"

  - name: Spotify
    <<: *platform_group
    icon: "https://raw.githubusercontent.com/ligonfei/Ligonfei/main/Spotify.png"

  - name: 游戏平台
    <<: *platform_group
    icon: "https://raw.githubusercontent.com/ligonfei/Ligonfei/main/Game.png"

  - name: GitHub
    <<: *platform_group
    icon: "https://raw.githubusercontent.com/ligonfei/Ligonfei/main/GitHub.png"

  - name: Bing
    <<: *platform_group
    icon: "https://raw.githubusercontent.com/ligonfei/Ligonfei/main/bing.png"

  - name: Microsoft
    <<: *platform_group
    icon: "https://raw.githubusercontent.com/ligonfei/Ligonfei/main/microsoft.png"

  - name: Google
    <<: *platform_group
    icon: "https://raw.githubusercontent.com/ligonfei/Ligonfei/main/google.png"

  - name: Apple
    <<: *platform_group
    icon: "https://raw.githubusercontent.com/ligonfei/Ligonfei/main/appleclassic.png"

  - name: 国内平台
    type: select
    proxies: [DIRECT, 节点选择]
    icon: "https://raw.githubusercontent.com/ligonfei/Ligonfei/main/China.png"
    lazy: false
    timeout: 5000

  - name: 漏网之鱼
    <<: *platform_group
    icon: "https://raw.githubusercontent.com/ligonfei/Ligonfei/main/fish.png"

  - name: 台湾节点
    <<: *country_nodes
    icon: "https://raw.githubusercontent.com/ligonfei/Ligonfei/main/Taiwan.png"
    filter: "(?i)(台湾|TW|Taiwan)"

  - name: 香港节点
    <<: *country_nodes
    icon: "https://raw.githubusercontent.com/ligonfei/Ligonfei/main/Hong_Kong.png"
    filter: "(?i)(香港|HK|Hong\\s*Kong)"

  - name: 日本节点
    <<: *country_nodes
    icon: "https://raw.githubusercontent.com/ligonfei/Ligonfei/main/Japan.png"
    filter: "(?i)(日本|JP|Japan)"

  - name: 美国节点
    <<: *country_nodes
    icon: "https://raw.githubusercontent.com/ligonfei/Ligonfei/main/United_States.png"
    filter: "(?i)(美国|US|USA|United\\s*States)"

  - name: 新加坡节点
    <<: *country_nodes
    icon: "https://raw.githubusercontent.com/ligonfei/Ligonfei/main/Singapore.png"
    filter: "(?i)(新加坡|SG|Singapore)"

  - name: 韩国节点
    <<: *country_nodes
    icon: "https://raw.githubusercontent.com/ligonfei/Ligonfei/main/Korea.png"
    filter: "(?i)(韩国|KR|Korea|South\\s*Korea)"

  - name: GLOBAL
    type: select
    proxies:
      - DIRECT
      - REJECT
      - 节点选择
      - 自动选择
      - 自建
      - 雪山
      - 西部数据
      - 山海
      - Kitty
      - 密码管理器
      - 交易所
      - AI
      - Speedtest
      - Telegram
      - 推特
      - YouTube
      - Disney+
      - NETFLIX
      - Spotify
      - 游戏平台
      - GitHub
      - Bing
      - Microsoft
      - Google
      - Apple
      - 国内平台
      - 漏网之鱼
      - 香港节点
      - 台湾节点
      - 美国节点
      - 日本节点
      - 韩国节点
      - 新加坡节点
    interval: 60
    lazy: false
    timeout: 5000
    icon: "https://raw.githubusercontent.com/ligonfei/Ligonfei/main/Global.png"

# 规则集配置
rule-providers:
  Fake-IP-Filter:
    <<: *domain
    path: ./rules/Fake-IP-Filter.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/raw/refs/heads/mihomo-ruleset/fakeip-filter.mrs"

  password_manager_domain:
    <<: *domain
    path: ./rules/password_manager.mrs
    url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-password-management.mrs"

  private_domain:
    <<: *domain
    path: ./rules/private.mrs
    url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/private.mrs"

  private_ip:
    <<: *ip
    path: ./rules/private_ip.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/raw/refs/heads/mihomo-ruleset/privateip.mrs"

  binance_domain:
    <<: *domain
    path: ./rules/binance.mrs
    url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/binance.mrs"

  OKX_domain:
    <<: *domain
    path: ./rules/okx.mrs
    url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/okx.mrs"

  bybit_domain:
    <<: *domain
    path: ./rules/bybit.mrs
    url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/bybit.mrs"

  gate_domain:
    <<: *domain
    path: ./rules/gate.mrs
    url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/gateio.mrs"

  ai_domain:
    <<: *domain
    path: ./rules/ai.mrs
    url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-ai-!cn.mrs"

  ai_ip:
    <<: *ip
    path: ./rules/ai_ip.mrs
    url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/ai.mrs"

  speedtest_domain:
    <<: *domain
    path: ./rules/speedtest.mrs
    url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-speedtest.mrs"

  telegram_domain:
    <<: *domain
    path: ./rules/telegram.mrs
    url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/telegram.mrs"

  telegram_ip:
    <<: *ip
    path: ./rules/telegram_ip.mrs
    url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/telegram.mrs"

  x_domain:
    <<: *domain
    path: ./rules/x.mrs
    url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/x.mrs"

  twitter_domain:
    <<: *domain
    path: ./rules/twitter.mrs
    url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/twitter.mrs"

  twitter_ip:
    <<: *ip
    path: ./rules/twitter_ip.mrs
    url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/twitter.mrs"

  youtube_domain:
    <<: *domain
    path: ./rules/youtube.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/raw/refs/heads/mihomo-ruleset/youtube.mrs"

  disney_domain:
    <<: *domain
    path: ./rules/disney.mrs
    url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/disney.mrs"

  netflix_domain:
    <<: *domain
    path: ./rules/netflix.mrs
    url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/netflix.mrs"

  netflix_ip:
    <<: *ip
    path: ./rules/netflix_ip.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/raw/refs/heads/mihomo-ruleset/netflixip.mrs"

  spotify_domain:
    <<: *domain
    path: ./rules/spotify.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/raw/refs/heads/mihomo-ruleset/spotify.mrs"

  epicgames_domain:
    <<: *domain
    path: ./rules/epicgames.mrs
    url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/epicgames.mrs"

  steam_domain:
    <<: *domain
    path: ./rules/steam.mrs
    url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/steam.mrs"

  xbox_domain:
    <<: *domain
    path: ./rules/xbox.mrs
    url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/xbox.mrs"

  rockstar_domain:
    <<: *domain
    path: ./rules/rockstar.mrs
    url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/rockstar.mrs"

  ubisoft_domain:
    <<: *domain
    path: ./rules/ubisoft.mrs
    url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/ubisoft.mrs"

  ea_domain:
    <<: *domain
    path: ./rules/ea.mrs
    url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/ea.mrs"

  gog_domain:
    <<: *domain
    path: ./rules/gog.mrs
    url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/gog.mrs"

  github_domain:
    <<: *domain
    path: ./rules/github.mrs
    url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/github.mrs"

  bing_domain:
    <<: *domain
    path: ./rules/bing.mrs
    url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/bing.mrs"

  microsoft_domain:
    <<: *domain
    path: ./rules/microsoft.mrs
    url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/microsoft.mrs"

  google_domain:
    <<: *domain
    path: ./rules/google.mrs
    url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/google.mrs"

  google_ip:
    <<: *ip
    path: ./rules/google_ip.mrs
    url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/google.mrs"

  apple_domain:
    <<: *domain
    path: ./rules/apple.mrs
    url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/apple.mrs"

  gfw_domain:
    <<: *domain
    path: ./rules/gfw.mrs
    url: "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/gfw.mrs"

  cn_domain:
    <<: *domain
    path: ./rules/cn.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/raw/refs/heads/mihomo-ruleset/cn.mrs"

  cn_ip:
    <<: *ip
    path: ./rules/cn_ip.mrs
    url: "https://github.com/DustinWin/ruleset_geodata/raw/refs/heads/mihomo-ruleset/cnip.mrs"

# 路由规则
rules:
  - DOMAIN-SUFFIX,sharedchat.cc,DIRECT
  - DOMAIN-SUFFIX,hybgzs.com,DIRECT
  - DST-PORT,22,DIRECT

  - RULE-SET,password_manager_domain,密码管理器

  - RULE-SET,private_domain,DIRECT
  - RULE-SET,private_ip,DIRECT,no-resolve

  - RULE-SET,binance_domain,交易所
  - RULE-SET,OKX_domain,交易所
  - RULE-SET,bybit_domain,交易所
  - RULE-SET,gate_domain,交易所

  - RULE-SET,ai_domain,AI
  - RULE-SET,ai_ip,AI,no-resolve

  - RULE-SET,speedtest_domain,Speedtest

  - RULE-SET,telegram_domain,Telegram
  - RULE-SET,telegram_ip,Telegram,no-resolve

  - RULE-SET,x_domain,推特
  - RULE-SET,twitter_domain,推特
  - RULE-SET,twitter_ip,推特,no-resolve

  - RULE-SET,youtube_domain,YouTube

  - RULE-SET,disney_domain,Disney+

  - RULE-SET,netflix_domain,NETFLIX
  - RULE-SET,netflix_ip,NETFLIX,no-resolve

  - RULE-SET,spotify_domain,Spotify

  - RULE-SET,epicgames_domain,DIRECT
  - RULE-SET,steam_domain,游戏平台
  - RULE-SET,xbox_domain,游戏平台
  - RULE-SET,rockstar_domain,游戏平台
  - RULE-SET,ubisoft_domain,游戏平台
  - RULE-SET,ea_domain,游戏平台
  - RULE-SET,gog_domain,游戏平台

  - RULE-SET,github_domain,GitHub

  - RULE-SET,bing_domain,Bing

  - RULE-SET,microsoft_domain,Microsoft

  - RULE-SET,google_domain,Google
  - RULE-SET,google_ip,Google,no-resolve

  - RULE-SET,apple_domain,Apple

  - RULE-SET,gfw_domain,节点选择


  - RULE-SET,cn_domain,国内平台
  - RULE-SET,cn_ip,国内平台,no-resolve

  - MATCH,漏网之鱼
